language: php

php:
  - 7.2

matrix:
    fast_finish: false

env:
    - LARAVEL_VERSION="5.6.*"

before_script:
  - composer install
  - composer require --no-update "laravel/laravel:${LARAVEL_VERSION}"

script:
  - vendor/bin/phpcs --extensions=php --standard=PSR2 app tests
  - vendor/bin/phpmd app tests text codesize,unusedcode,naming
  - vendor/bin/phpcpd app
  - vendor/bin/phpunit --no-coverage