version: '3'
services:
    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./:/var/www/html
    nginx:
        image: nginx:latest
        links:
            - php-fpm
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/vhost/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    yarn:
        image: node:latest
        links: 
            - php-fpm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        tty: true

    mongo:
        image: 'bitnami/mongodb:latest'
        ports:
          - "27017:27017"
        environment:
          - MONGODB_USERNAME=mongo
          - MONGODB_PASSWORD=password
          - MONGODB_DATABASE=blog

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=blog
            - MYSQL_USER=blog
            - MYSQL_PASSWORD=password
        ports:
            - "3309:3306"